# Generated by Django 3.1.2 on 2020-10-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20201030_0916'),
        ('standsreview', '0002_auto_20201030_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decision',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='submission.submission'),
        ),
    ]
