- name: Set up base
  include: skeleton.yml
- name: Set up Python
  include: python.yml
- name: Install application
  include: code.yml
  become: yes
  become_user: fosdem_submission
  become_method: sudo
- name: Set up proxy and web server
  include: management.yml