- name: Install dependencies
  apt:
    name:
      - nginx
    state: present
- name: Create application path
  file:
    path: /var/opt/app/fosdem_submission/static
    state: directory
    owner: fosdem_submission
    group: fosdem_submission
- name: Create systemd service file
  template:
    dest: /etc/systemd/system/fosdem_submission.service
    src: fosdem_submission.service.j2
- name: Start tool
  systemd:
    name: fosdem_submission
    state: started
    enabled: yes
    daemon_reload: yes
- name: Install nginx configuration file
  copy:
    dest: /etc/nginx/conf.d/fosdem_submission.conf
    src: nginx.conf
- name: Reload nginx
  service:
    name: nginx
    state: reloaded