# Generated by Django 3.1.4 on 2020-12-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(blank=True, default='', verbose_name='Comments'),
        ),
    ]
