# Generated by Django 3.1.4 on 2021-01-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20210105_1544'),
        ('review', '0002_auto_20201213_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='E-mail contents')),
                ('edition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_submissions_mail', to='submission.fosdemedition')),
            ],
        ),
    ]
