# Generated by Django 3.1.2 on 2020-10-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='notes',
            field=models.TextField(null=True, verbose_name='Comments'),
        ),
    ]
