# Generated by Django 3.1.4 on 2020-12-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20201213_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='FOSDEMEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5, verbose_name='Edition')),
            ],
        ),
        migrations.CreateModel(
            name='FOSDEMStandsEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submissions_open', models.BooleanField(default=False, verbose_name='Submissions open')),
                ('accepted_announced', models.BooleanField(default=False, verbose_name='Accepted submissions announced')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.fosdemedition')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='edition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='submission.fosdemstandsedition'),
        ),
    ]
