# Generated by Django 3.1.4 on 2021-01-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0005_theme_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitaledition',
            name='stand_website_code',
            field=models.URLField(null=True, verbose_name='Location of content files'),
        ),
        migrations.AddField(
            model_name='digitaledition',
            name='stand_website_static',
            field=models.URLField(null=True, verbose_name='Location static files'),
        ),
    ]
