# Generated by Django 3.1.4 on 2021-01-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0006_auto_20210103_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitaledition',
            name='stand_website_static',
            field=models.URLField(null=True, verbose_name='Location of static files'),
        ),
    ]
