# Generated by Django 4.1.1 on 2022-09-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0007_auto_20210105_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosdemstandsedition',
            name='description',
            field=models.TextField(null=True, verbose_name='Blurb for the submissions page'),
        ),
    ]
