- name: Download latest release
  get_url:
    url: "https://github.com/pieterdp/fosdem-stand-submission/archive/{{version}}.tar.gz"
    dest: /var/opt/app/fosdem_submission/source.tar.gz
- name: Extract release
  unarchive:
    src: /var/opt/app/fosdem_submission/source.tar.gz
    remote_src: yes
    dest: /var/opt/app/fosdem_submission
- name: Install dependencies
  pip:
    chdir: "/var/opt/app/fosdem_submission/fosdem-stand-submission-{{version}}"
    requirements: requirements.txt
    virtualenv: "/var/opt/app/fosdem_submission/{{version}}-venv"
- name: Configure the application
  include_tasks: config.yml
- name: Run migrations
  community.general.django_manage:
    command: 'migrate'
    project_path: "/var/opt/app/fosdem_submission/fosdem-stand-submission-{{version}}/standssubmission"
    virtualenv: "/var/opt/app/fosdem_submission/{{version}}-venv"
- name: Collect static files
  community.general.django_manage:
    command: 'collectstatic'
    project_path: "/var/opt/app/fosdem_submission/fosdem-stand-submission-{{version}}/standssubmission"
    virtualenv: "/var/opt/app/fosdem_submission/{{version}}-venv"